[package]
name = "ned"
version = "0.1.10"
authors = ["Nev Delap <nevdelap@gmail.com>"]

[dependencies]
ansi_term = "0.7.*"
getopts = "0.2.*"
glob = "0.2.*"
regex = "0.1.*"
walkdir = "0.1.*"

[profile.release]
lto = true